export const PHOTO_PICKER: string = 'photo-picker'
export const CONTEXT_OPENED: string = 'context-opened'
export const PHOTO_PICKER_ELEMENT: string = 'photo-picker-element'
export const PHOTO_PICKER_MESSAGE: string = 'photo-picker-message'
export const CHANGE_BG_IMAGE: string = 'change-bg-image'
export const PHOTO_PICKER_MESSAGE_ELEMENT: string =
	'photo-picker-message-element'
export const EMOJI_ID_REF: string = 'emoji-id-open-ref'
export const VOICE_CALL_REF: string = 'voice-call-open-ref'
export const VIDEO_CALL_REF: string = 'video-call-open-ref'
